#!/usr/bin/env python
database = {"p450": ["Cytochrome_450", "#ff0000", "RE"],
            "Terpene_synth_C": ["Terpene_synthase", "#35F800", "RE"],
            "SQHop_cyclase_C": ["Terpene_synthase", "#35F800", "RE"],
            "SQHop_cyclase_N": ["Terpene_synthase", "#35F800", "RE"],
            "SQHop_cyclase_C,SQHop_cyclase_N": ["Terpene_synthase", "#35F800", "RE"],
            "SQHop_cyclase_N,SQHop_cyclase_C": ["Terpene_synthase", "#35F800", "RE"],
            "Terpene_synth": ["Terpene_synthase", "#35F800", "RE"],
            "Lycopene_cycl": ["Terpene_synthase", "#35F800", "RE"],
            "Cu_amine_oxid": ["Copper amine oxidase", "#E9C63E", "RE"],
            "Bet_v_1": ["Pictet-Spengler enzyme (Bet v1)", "#735100", "RE"],
            "Glycos_transf_1": ["Glycosyltransferase", "#F477A6", "RE"],
            "Glycos_transf_2": ["Glycosyltransferase", "#F477A6", "RE"],
            "Glyco_transf_28": ["Glycosyltransferase", "#F477A6", "RE"],
            "UDPGT": ["Glycosyltransferase", "#F477A6", "RE"],
            "UDPGT_2": ["Glycosyltransferase", "#F477A6", "RE"],
            "Chal_sti_synt_C": ["Ketosynthase", "#75FFD8", "RE"],
            "Chal_sti_synt_N": ["Ketosynthase", "#75FFD8", "RE"],
            "SE": ["Squalene epoxidase", "#206B14", "RE"], "COesterase": ["COesterase", "#A221FF", "RE"],
            "Methyltransf_2": ["Methyltransferase", "#CF0FFF", "RE"],
            "Methyltransf_3": ["Methyltransferase", "#CF0FFF", "RE"],
            "Methyltransf_7": ["Methyltransferase", "#CF0FFF", "RE"],
            "Methyltransf_11": ["Methyltransferase", "#CF0FFF", "RE"],
            "cMT": ["Methyltransferase", "#CF0FFF", "RE"], "nMT": ["Methyltransferase", "#CF0FFF", "RE"],
            "oMT": ["Methyltransferase", "#CF0FFF", "RE"],
            "Transferase": ["BAHD acyltransferase", "#0003EC", "RE"],
            "Peptidase_S10": ["Scl acyltransferase", "#0c126d", "RE"],
            "Epimerase": ["Epimerase", "#F245BD", "RE"],
            "adh_short": ["Oxidoreductase", "#4DD0E1", "RE"],
            "adh_short_C2": ["Oxidoreductase", "#4DD0E1", "RE"],
            "NAD_binding_1": ["Oxidoreductase", "#4DD0E1", "RE"],
            "GMC_oxred_N": ["Oxidoreductase", "#4DD0E1", "RE"],
            "GMC_oxred_C": ["Oxidoreductase", "#4DD0E1 ", "RE"], "DIOX_N": ["Dioxygenase", "#F5B2FF", "RE"],
            "2OG-FeII_Oxy": ["Dioxygenase", "#F5B2FF", "RE"],
            "AMP-binding": ["CoA-ligase", "#8F400B", "RE"], "Amino_oxidase": ["Amino oxidase", "#2C113A", "RE"],
            "Aminotran_1_2": ["Aminotransferase", "#E42E00", "RE"],
            "Aminotran_3": ["Aminotransferase", "#E42E00", "RE"],
            "Prenyltrans": ["Prenyltransferase", "#552288", "RE"],
            "Prenyltransf": ["Prenyltransferase", "#552288", "RE"],
            "UbiA": ["Prenyltransferase", "#552288", "RE"],
            "Str_synth": ["Strictosidine synthase-like", "#dd71dd", "RE"],
            "PRISE": ["PRISE enzymes", "#13C600", "RE"], "Dirigent": ["Dirigent enzymes", "#606000", "RE"]
            }
